import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TrpcProvider from "@/lib/trpc/Provider";
import NextAuthProvider from "@/lib/auth/Provider";
const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Chat App | FriendZone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
<TrpcProvider>
<NextAuthProvider>{children}</NextAuthProvider>
</TrpcProvider>
</body>
    </html>
  );
}
